### ISSUE TITLE
Download.py 

### ISSUE THREAD

**Issue by hadarisas** [segnolin/google-drive-folder-downloader#1]
Hii
I Just came to run your script with target folder  and the destination path as a parameter, and it work good.
I just have one issue if you could help with, I want to run the script without download confirmation

**Comment by segnolin** [comment]
What do you mean about the download confirmation? Please be specific. If you mean the browser pop up at the first time of downloading, that is necessary because it tries to obtain the token form google, and it only needs once.

**Comment by hadarisas** [comment]
Not the browser popup
I mean the (Y or N) to confirm the start downloading for each file
Also is there a way to specify  the download only from one folder from drive
Best regards

**Comment by segnolin** [comment]
Didn’t encounter that issue. I tried the script on macOS 10.14 and ubuntu 18.04 and it was fine.
Can you provide the environment details or some screenshots? Thanks!

“is there a way to specify the download only from one folder from drive”
I think my script just did that?
