### ISSUE TITLE
ASK BRO

### ISSUE THREAD

**Issue by nikolaibarbravas** [segnolin/google-drive-folder-downloader#7]
This tools can download shared file ? im not owner .

**Comment by segnolin** [comment]
You can download it once the content is in the “Shared with me” section. You don’t have to be the owner.

**Comment by nikolaibarbravas** [comment]
yes bro this script working good. but if the file on drive example the size is 10tb and my hardisk only 1tb when im download that i just got 1tb and -9 not downloaded. so if i cut my downloaded file to another drive and resume the 9tb its can bro or start from 0 again ? sorry bad english... 
and the simple thing actualy i need google migrator .. ( shared file) copy to my own drive bro. if you can make it please. because im trying tools on chrome store thats cant resume after got limit 750gb/day.. force close

**Comment by nikolaibarbravas** [comment]
shared file) copy to my own google drive bro

**Comment by segnolin** [comment]
> yes bro this script working good. but if the file on drive example the size is 10tb and my hardisk only 1tb when im download that i just got 1tb and -9 not downloaded. so if i cut my downloaded file to another drive and resume the 9tb its can bro or start from 0 again ? sorry bad english...
> and the simple thing actualy i need google migrator .. ( shared file) copy to my own drive bro. if you can make it please. because im trying tools on chrome store thats cant resume after got limit 750gb/day.. force close

Currently there is no support for such function, but I have some tricks.
- You can create empty file with the same file name as the downloaded one, so the script would think that the files are already downloaded and start to download the new files.
- Or, you can remove one line code `os.remove(location + filename)` so the script won't automatically remove incomplete file so that you can Ctrl+C the script several times to create empty file in order to trick the script as the above mentioned.

**Comment by segnolin** [comment]
> shared file) copy to my own google drive bro

I do have the [script](https://gist.github.com/segnolin/cc05ac1bb8c461d49dde00b6a026188f) (Google App Script) to do such thing, but you have to figure out the environment settings of app script or so. I cannot help a lot. After all this topic is already digression.

This script is not stable, so use it at your own risk. In addition, the script would timeout if you have too many files to copy (the limit is 1800s if I remember).

I might repost the code somewhere else once I think it's stable enough, so the above link is temporary.
