### ISSUE TITLE
Doesn't seem to work in console

### ISSUE THREAD

**Issue by AwesomeLemon** [segnolin/google-drive-folder-downloader#8]
Hi,
I'm trying to download some files by running the script from the console on a server without GUI (via ssh). I can't pass the google authentication: it opens the text-based console browser, and asks for email & password, and then fails due to JavaScript not being supported.
Could you tell me whether it is possible to use the script without GUI? 
[I've enabled Google Drive API; copied credentials.json to the working directory; installed all the packages]

**Comment by segnolin** [comment]
Hi,

I only test it under the GUI environment, but I guess it could work if you first run the script on your host machine that has GUI (and do the authentication with your browser), and copy the `token.pickle` file, which is the authentication file, to remote server.

See if it works, thanks!

**Comment by AwesomeLemon** [comment]
It worked perfectly, thank you!
